// End-to-end checks for the Vehicle Sales API (POST/GET /shop/vehicle-sales) against a real deployment
// (default: a local bootstrap server on :4100; set SMOKE_TEST_BASE_URL for the live function). Creates two
// throwaway shops ("Audit Fix Shop vehicle sales ...", removed by cleanup-test-data.ts).
//
//   SMOKE_TEST_BASE_URL=https://api-roe6cy7kca-uc.a.run.app npx ts-node -r tsconfig-paths/register scripts/smoke-test-vehicle-sales.ts
import * as fs from 'fs';
import * as path from 'path';
process.env.FIREBASE_SERVICE_ACCOUNT_JSON = fs.readFileSync(
  path.join(__dirname, '../firebase-service-account-old.json'),
  'utf8',
);

const BASE = (process.env.SMOKE_TEST_BASE_URL || 'http://127.0.0.1:4100') + '/api';
const octet = () => Math.floor(Math.random() * 250);
const randomIp = () => `10.${octet()}.${octet()}.${octet()}`;

async function req(method: string, p: string, body?: any, token?: string) {
  const res = await fetch(`${BASE}${p}`, {
    method,
    headers: { 'Content-Type': 'application/json', 'X-Forwarded-For': randomIp(), ...(token ? { Authorization: `Bearer ${token}` } : {}) },
    body: body ? JSON.stringify(body) : undefined,
  });
  const text = await res.text();
  let parsed: any; try { parsed = JSON.parse(text); } catch { parsed = text; }
  return { status: res.status, body: parsed };
}
let failures = 0;
const check = (label: string, ok: boolean, detail?: any) => {
  if (!ok) failures++;
  console.log(`${ok ? 'PASS' : 'FAIL'}  ${label}${ok ? '' : '  -> ' + String(JSON.stringify(detail) ?? 'no detail').slice(0, 300)}`);
};

async function makeShop(label: string) {
  const suffix = `${Date.now()}${Math.floor(Math.random() * 90 + 10)}`;
  const phone = `9${suffix.slice(-9)}`;
  const sent = await req('POST', '/auth/send-otp', { identifier: phone, purpose: 'register' });
  if (!sent.body?.devCode) throw new Error('no devCode - is OTP_SHOW_CODE_IN_UI on? ' + JSON.stringify(sent));
  await req('POST', '/auth/verify-otp', { identifier: phone, purpose: 'register', code: sent.body.devCode });
  const reg = await req('POST', '/auth/register-shop', {
    shopName: `Audit Fix Shop vehicle sales ${label} ${suffix}`, ownerName: `Owner ${label}`, phone, password: 'SalesPass123',
    location: 'Test Address', town: 'Chennai', district: 'Chennai', categoryId: 'key-shops', startTrial: true,
  });
  const login = await req('POST', '/auth/login', { email: phone, password: 'SalesPass123', platform: 'native' });
  if (reg.status !== 201 || !login.body?.accessToken) throw new Error('could not create shop ' + label + ' ' + JSON.stringify([reg, login.status]));
  return { shopId: reg.body.shopId as string, token: login.body.accessToken as string };
}

const SALE = {
  saleDate: '2026-10-03', saleTime: '14:30',
  sellerName: 'முருகன்', sellerAddress: '12, காந்தி சாலை, சேலம்', sellerPhone: '9876543210',
  buyerName: 'Rajesh Kumar', buyerAddress: '5 Park Street, Chennai', buyerPhone: '+91 98765 43211',
  registrationNumber: 'TN30AB1234', vehicleModel: 'Splendor Plus', vehicleColor: 'கருப்பு', vehicleName: 'Hero Splendor',
  chassisNumber: 'MBLHA10AMJ9A12345', engineNumber: 'HA10EJ9A12345',
  vehiclePrice: 45000, advanceAmount: 10000, officeCommission: 500, balanceLastDate: '2026-11-03',
  witnessName: 'Suresh', witnessAddress: 'Salem', notes: 'RC book with seller', lang: 'ta',
};

async function main() {
  const { FirestoreService } = await import('../src/firestore/firestore.service');
  const db = new FirestoreService().db;

  console.log('--- Auth ---');
  const anon = await req('GET', '/shop/vehicle-sales');
  check('listing without a token is rejected (401)', anon.status === 401, anon.status);
  const anonPost = await req('POST', '/shop/vehicle-sales', SALE);
  check('creating without a token is rejected (401)', anonPost.status === 401, anonPost.status);

  const A = await makeShop('A');
  const B = await makeShop('B');
  console.log(`shops: A=${A.shopId} B=${B.shopId}`);

  console.log('\n--- Create (valid, Tamil text, client tries to forge fields) ---');
  const forged = { ...SALE, balanceAmount: 1, shopId: B.shopId, createdById: 'someone-else', deletedAt: 5, createdAt: 1, id: 'forged-id', saleNumber: undefined };
  const c1 = await req('POST', '/shop/vehicle-sales', forged, A.token);
  check('sale created (201)', c1.status === 201, c1);
  const sale1 = c1.body;
  check('Tamil / Unicode text is preserved exactly', sale1.sellerName === 'முருகன்' && sale1.vehicleColor === 'கருப்பு' && sale1.sellerAddress === '12, காந்தி சாலை, சேலம்', { sellerName: sale1.sellerName });
  check('balance is computed on the server (45000 - 10000 = 35000), not taken from the client', sale1.balanceAmount === 35000, sale1.balanceAmount);
  const NUMBER_FORMAT = /^VS-[1-9]\d{9}$/;
  check('receipt number is generated by the server (VS- + 10 random digits)', NUMBER_FORMAT.test(sale1.saleNumber), sale1.saleNumber);
  check('buyer phone is normalised to 10 digits', sale1.buyerPhone === '9876543211', sale1.buyerPhone);
  check('invoice language is stored', sale1.lang === 'ta', sale1.lang);

  const doc = (await db.collection('shops').doc(A.shopId).collection('vehicleSales').doc(sale1.id).get()).data() as any;
  check('stored under the caller\'s own shop (shops/A/vehicleSales)', !!doc, 'missing');
  check('forged id / shopId / createdById / createdAt / deletedAt are NOT honoured', sale1.id !== 'forged-id' && doc.shopId === A.shopId && doc.createdById !== 'someone-else' && doc.createdAt > 1000 && doc.deletedAt === null, { createdById: doc?.createdById, createdAt: doc?.createdAt, deletedAt: doc?.deletedAt, shopId: doc?.shopId });
  const bDoc = await db.collection('shops').doc(B.shopId).collection('vehicleSales').doc(sale1.id).get();
  check('nothing was written under shop B despite the forged shopId', !bDoc.exists);

  const c2 = await req('POST', '/shop/vehicle-sales', { ...SALE, registrationNumber: 'TN30CD5678', advanceAmount: undefined, officeCommission: undefined }, A.token);
  check('second sale gets its own, different number and a zero advance', c2.status === 201 && NUMBER_FORMAT.test(c2.body.saleNumber) && c2.body.saleNumber !== sale1.saleNumber && c2.body.advanceAmount === 0 && c2.body.balanceAmount === 45000, c2.body);
  const c3 = await req('POST', '/shop/vehicle-sales', { ...SALE, registrationNumber: 'TN30EF9999', saleNumber: 'MY-100' }, A.token);
  check('a receipt number sent by the client is ignored', c3.status === 201 && c3.body.saleNumber !== 'MY-100' && NUMBER_FORMAT.test(c3.body.saleNumber), c3.body?.saleNumber);
  const numbers = [sale1.saleNumber, c2.body.saleNumber, c3.body.saleNumber];
  check('all receipt numbers are distinct', new Set(numbers).size === 3, numbers);
  const idx = await Promise.all(numbers.map((n) => db.collection('vehicleSaleNumbers').doc(n).get()));
  check('each number is claimed in vehicleSaleNumbers (the uniqueness index)', idx.every((d) => d.exists) && (idx[0].data() as any).shopId === A.shopId, idx.map((d) => d.exists));

  console.log('\n--- Validation ---');
  const bad = async (label: string, override: any) => {
    const r = await req('POST', '/shop/vehicle-sales', { ...SALE, ...override }, A.token);
    check(`${label} -> 400`, r.status === 400, r.status);
  };
  await bad('missing buyer name', { buyerName: '' });
  await bad('missing seller name', { sellerName: undefined });
  await bad('missing registration number', { registrationNumber: ' ' });
  await bad('zero price', { vehiclePrice: 0 });
  await bad('advance bigger than the price', { advanceAmount: 99999 });
  await bad('negative commission', { officeCommission: -5 });
  await bad('malformed date', { saleDate: '03-10-2026' });
  await bad('unsupported language', { lang: 'fr' });
  await bad('object instead of text', { buyerName: { a: 1 } });
  await bad('absurdly long address', { buyerAddress: 'x'.repeat(1000) });
  const before = (await db.collection('shops').doc(A.shopId).collection('vehicleSales').get()).size;
  check('rejected requests stored nothing (still 3 sales)', before === 3, before);

  console.log('\n--- List / get / isolation ---');
  const list = await req('GET', '/shop/vehicle-sales', undefined, A.token);
  check('list returns the 3 sales, newest first', Array.isArray(list.body) && list.body.length === 3 && list.body[0].saleNumber === c3.body.saleNumber, list.body?.map?.((s: any) => s.saleNumber));
  const limited = await req('GET', '/shop/vehicle-sales?limit=1', undefined, A.token);
  check('limit works', Array.isArray(limited.body) && limited.body.length === 1, limited.body?.length);
  const get = await req('GET', `/shop/vehicle-sales/${sale1.id}`, undefined, A.token);
  check('a sale can be fetched by id', get.status === 200 && get.body.registrationNumber === 'TN30AB1234', get.status);
  const crossGet = await req('GET', `/shop/vehicle-sales/${sale1.id}`, undefined, B.token);
  check("another shop cannot read it by id (404)", crossGet.status === 404, crossGet.status);
  const bList = await req('GET', '/shop/vehicle-sales', undefined, B.token);
  check("another shop's list is empty", Array.isArray(bList.body) && bList.body.length === 0, bList.body);
  const missing = await req('GET', '/shop/vehicle-sales/does-not-exist', undefined, A.token);
  check('unknown id -> 404', missing.status === 404, missing.status);

  console.log('\n--- Simultaneous sales get distinct receipt numbers ---');
  const burst = await Promise.all(Array.from({ length: 12 }, (_, i) => req('POST', '/shop/vehicle-sales', { ...SALE, registrationNumber: `TN30BU${1000 + i}` }, A.token)));
  const burstNumbers = burst.map((x) => x.body?.saleNumber);
  check('12 simultaneous sales all succeed with 12 distinct numbers', burst.every((x) => x.status === 201) && new Set(burstNumbers).size === 12, burstNumbers);

  console.log('\n--- Photos (max 5 per sale) ---');
  // Needs file storage: run against the Storage emulator (FIREBASE_STORAGE_EMULATOR_HOST) or a deployed API.
  const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==', 'base64');
  const upload = async (saleId: string, token: string, type = 'image/png', bytes: Buffer = png, name = 'p.png') => {
    const fd = new FormData();
    fd.append('file', new Blob([new Uint8Array(bytes)], { type }), name);
    const res = await fetch(`${BASE}/shop/vehicle-sales/${saleId}/photos`, { method: 'POST', headers: { Authorization: `Bearer ${token}` }, body: fd });
    return { status: res.status, body: await res.json().catch(() => ({})) };
  };
  const photoSale = (await req('POST', '/shop/vehicle-sales', { ...SALE, registrationNumber: 'TN30PH0001' }, A.token)).body;
  const noToken = await fetch(`${BASE}/shop/vehicle-sales/${photoSale.id}/photos`, { method: 'POST', body: new FormData() });
  check('uploading without a token is rejected (401)', noToken.status === 401, noToken.status);
  for (let n = 1; n <= 5; n++) {
    const r = await upload(photoSale.id, A.token);
    check(`photo ${n} of 5 is accepted`, r.status === 201 && r.body.photos?.length === n, r);
  }
  const sixth = await upload(photoSale.id, A.token);
  check('a 6th photo is refused (400)', sixth.status === 400 && /at most 5/.test(sixth.body.message || ''), sixth);
  const pdfUpload = await upload((await req('POST', '/shop/vehicle-sales', { ...SALE, registrationNumber: 'TN30PH0002' }, A.token)).body.id, A.token, 'application/pdf', Buffer.from('%PDF-1.4'), 'x.pdf');
  check('a PDF is refused as a photo (400)', pdfUpload.status === 400, pdfUpload.status);
  const crossUpload = await upload(photoSale.id, B.token);
  check("another shop cannot add photos to this sale (404)", crossUpload.status === 404, crossUpload.status);
  const stored = (await db.collection('shops').doc(A.shopId).collection('vehicleSales').doc(photoSale.id).get()).data() as any;
  check('exactly 5 photos are stored on the sale, each with a file key and URL', stored.photos?.length === 5 && stored.photos.every((p: any) => p.key && p.url), stored.photos?.length);
  const withPhotos = await req('GET', `/shop/vehicle-sales/${photoSale.id}`, undefined, A.token);
  check('GET returns the sale with its 5 photos', withPhotos.status === 200 && withPhotos.body.photos?.length === 5, withPhotos.body?.photos?.length);
  const concurrent = (await req('POST', '/shop/vehicle-sales', { ...SALE, registrationNumber: 'TN30PH0003' }, A.token)).body;
  const race = await Promise.all(Array.from({ length: 8 }, () => upload(concurrent.id, A.token)));
  const stored2 = (await db.collection('shops').doc(A.shopId).collection('vehicleSales').doc(concurrent.id).get()).data() as any;
  check('8 simultaneous uploads: exactly 5 succeed, 3 are refused, 5 stored', race.filter((x) => x.status === 201).length === 5 && race.filter((x) => x.status === 400).length === 3 && stored2.photos.length === 5, race.map((x) => x.status));

  // ---------------------------------------------------------------------------------------------------------
  // Super Admin: own sales (no shop) + the platform-wide review. Creates a throwaway Super Admin account, so this
  // section only runs against the emulators - never against the live project.
  console.log('\n--- Super Admin sales and review ---');
  if (!process.env.FIRESTORE_EMULATOR_HOST) {
    console.log('SKIPPED (needs the Firebase emulators: FIRESTORE_EMULATOR_HOST / FIREBASE_AUTH_EMULATOR_HOST)');
  } else {
    const { FirebaseAuthService } = await import('../src/firestore/auth/firebase-auth.service');
    const auth = new FirebaseAuthService();
    const stamp = Date.now();
    const adminEmail = `super-sales-${stamp}@example.com`;
    const adminUser = await auth.createUser({ email: adminEmail, password: 'SuperPass123', displayName: 'Platform Boss' });
    await db.collection('users').doc(adminUser.uid).set({ email: adminEmail, phone: null, name: 'Platform Boss', role: 'SUPER_ADMIN', shopId: null, deletedAt: null, createdAt: stamp, updatedAt: stamp });
    await auth.setCustomClaims(adminUser.uid, { role: 'SUPER_ADMIN', shopId: null });
    const adminLogin = await req('POST', '/auth/login', { email: adminEmail, password: 'SuperPass123', platform: 'native' });
    const S = adminLogin.body.accessToken as string;
    check('Super Admin can log in for the test', !!S, adminLogin);

    // create under the Super Admin's own name - no shop is involved or accepted
    const forgedOwner = { ...SALE, registrationNumber: 'TN30SA0001', shopId: A.shopId, ownerType: 'SHOP', ownerName: 'Hacked' };
    const sa1 = await req('POST', '/super/vehicle-sales', forgedOwner, S);
    check('Super Admin creates a sale (201)', sa1.status === 201, sa1);
    check('it is owned by the Super Admin: no shop, their name, a generated receipt number',
      sa1.body.ownerType === 'SUPER_ADMIN' && sa1.body.shopId === null && sa1.body.ownerName === 'Platform Boss' && /^VS-[1-9]\d{9}$/.test(sa1.body.saleNumber), sa1.body);
    const storedSuper = (await db.collection('users').doc(adminUser.uid).collection('vehicleSales').doc(sa1.body.id).get()).data() as any;
    check('stored under the Super Admin user document (users/{uid}/vehicleSales)', !!storedSuper && storedSuper.ownerType === 'SUPER_ADMIN', storedSuper);
    const leaked = await db.collection('shops').doc(A.shopId).collection('vehicleSales').doc(sa1.body.id).get();
    check('a client-supplied shopId does not put it under a shop', !leaked.exists);

    // a sale for shop B too, so the review spans several shops
    const bSale = await req('POST', '/shop/vehicle-sales', { ...SALE, registrationNumber: 'TN30BB0001' }, B.token);
    check('shop B records a sale for the review test', bSale.status === 201 && bSale.body.shopId === B.shopId, bSale.status);

    // role walls
    const shopCallsSuper = await req('POST', '/super/vehicle-sales', { ...SALE, registrationNumber: 'TN30SA0002' }, A.token);
    check('a Shop Admin cannot use the Super Admin sales route (403)', shopCallsSuper.status === 403, shopCallsSuper.status);
    const shopReview = await req('GET', '/super/all-vehicle-sales', undefined, A.token);
    check('a Shop Admin cannot open the all-sales review (403)', shopReview.status === 403, shopReview.status);
    const superOnShopRoute = await req('POST', '/shop/vehicle-sales', { ...SALE, registrationNumber: 'TN30SA0003' }, S);
    check('the shop route still refuses a Super Admin (403)', superOnShopRoute.status === 403, superOnShopRoute.status);
    const noAuthReview = await req('GET', '/super/all-vehicle-sales');
    check('the review needs a login (401)', noAuthReview.status === 401, noAuthReview.status);

    // own list / get are scoped to the Super Admin, and shops never see it
    const ownList = await req('GET', '/super/vehicle-sales', undefined, S);
    check("the Super Admin's own list contains only their sales", Array.isArray(ownList.body) && ownList.body.length === 1 && ownList.body[0].id === sa1.body.id, ownList.body?.length);
    const aList = await req('GET', '/shop/vehicle-sales', undefined, A.token);
    check("a shop's list does not contain the Super Admin's sale", Array.isArray(aList.body) && !aList.body.some((x: any) => x.id === sa1.body.id), aList.body?.length);
    const shopGetsSuperSale = await req('GET', `/shop/vehicle-sales/${sa1.body.id}`, undefined, A.token);
    check("a shop cannot fetch the Super Admin's sale by id (404)", shopGetsSuperSale.status === 404, shopGetsSuperSale.status);
    const superGet = await req('GET', `/super/vehicle-sales/${sa1.body.id}`, undefined, S);
    check('the Super Admin can fetch their own sale by id', superGet.status === 200 && superGet.body.registrationNumber === 'TN30SA0001', superGet.status);

    // photos on a Super Admin sale: same rules (max 5)
    const upS = async (id: string, token: string, route = 'super') => {
      const fd = new FormData();
      fd.append('file', new Blob([new Uint8Array(png)], { type: 'image/png' }), 'p.png');
      const r = await fetch(`${BASE}/${route}/vehicle-sales/${id}/photos`, { method: 'POST', headers: { Authorization: `Bearer ${token}` }, body: fd });
      return { status: r.status, body: await r.json().catch(() => ({})) };
    };
    for (let n = 1; n <= 5; n++) { const r = await upS(sa1.body.id, S); check(`Super Admin photo ${n} of 5 accepted`, r.status === 201 && r.body.photos?.length === n, r); }
    const sixthS = await upS(sa1.body.id, S);
    check("a 6th photo on the Super Admin's sale is refused (400)", sixthS.status === 400, sixthS);
    const shopPhotoOnSuper = await upS(sa1.body.id, A.token, 'shop');
    check("a shop cannot add photos to the Super Admin's sale (404)", shopPhotoOnSuper.status === 404, shopPhotoOnSuper.status);

    // the review: every owner in one list
    const review = await req('GET', '/super/all-vehicle-sales?limit=100', undefined, S);
    const all: any[] = review.body?.items || [];
    check('the review returns sales from several shops and the Super Admin', review.status === 200 && all.some((x) => x.shopId === A.shopId) && all.some((x) => x.shopId === B.shopId) && all.some((x) => x.ownerType === 'SUPER_ADMIN'), [review.status, all.length]);
    check('every row names who sold it', all.length > 0 && all.every((x) => typeof x.ownerName === 'string' && x.ownerName.length > 0), all.filter((x) => !x.ownerName).length);
    check('shop rows carry their shop id and the Super Admin row has none', all.filter((x) => x.ownerType === 'SHOP').every((x) => !!x.shopId) && all.find((x) => x.id === sa1.body.id)?.shopId === null);
    check('the review is newest first', all.every((x, k) => k === 0 || all[k - 1].createdAt >= x.createdAt));
    check("the review includes each sale's photos", (all.find((x) => x.id === sa1.body.id)?.photos || []).length === 5, all.find((x) => x.id === sa1.body.id)?.photos?.length);
    const sameNumbers = all.map((x) => x.saleNumber);
    check('receipt numbers are unique across shops and the Super Admin', new Set(sameNumbers).size === sameNumbers.length, sameNumbers.length);

    // filters
    const onlyA = (await req('GET', `/super/all-vehicle-sales?limit=100&shopId=${A.shopId}`, undefined, S)).body.items || [];
    check('filtering by a shop returns only that shop\'s sales', onlyA.length > 0 && onlyA.every((x: any) => x.shopId === A.shopId), onlyA.length);
    const onlySuper = (await req('GET', '/super/all-vehicle-sales?limit=100&shopId=SUPER_ADMIN', undefined, S)).body.items || [];
    check("filtering by Super Admin returns only the Super Admin's sales", onlySuper.length >= 1 && onlySuper.every((x: any) => x.ownerType === 'SUPER_ADMIN' && x.shopId === null) && onlySuper.some((x: any) => x.id === sa1.body.id), onlySuper.length);
    const badShop = await req('GET', '/super/all-vehicle-sales?shopId=a%2Fb', undefined, S);
    check('a malformed shopId is refused (400)', badShop.status === 400, badShop.status);

    // paging with a cursor
    const p1 = (await req('GET', '/super/all-vehicle-sales?limit=3', undefined, S)).body;
    check('page 1 has 3 sales and a cursor', p1.items?.length === 3 && typeof p1.nextCursor === 'string', [p1.items?.length, p1.nextCursor]);
    const p2 = (await req('GET', `/super/all-vehicle-sales?limit=3&cursor=${encodeURIComponent(p1.nextCursor)}`, undefined, S)).body;
    check('page 2 continues without repeating page 1', p2.items?.length > 0 && p2.items.every((x: any) => !p1.items.some((y: any) => y.id === x.id)), p2.items?.length);
    const badCursor = await req('GET', '/super/all-vehicle-sales?cursor=customers%2Fabc', undefined, S);
    check('a cursor that is not a sale path is refused (400)', badCursor.status === 400, badCursor.status);

    // a sale from before owners were recorded: still shown, owner read from its path
    const legacy = db.collection('shops').doc(A.shopId).collection('vehicleSales').doc();
    await legacy.set({ registrationNumber: 'TN30OLD001', saleNumber: `VS-OLD-${stamp}`, buyerName: 'Old', sellerName: 'Old', vehiclePrice: 1000, advanceAmount: 0, balanceAmount: 1000, lang: 'en', createdAt: 1000, updatedAt: 1000, deletedAt: null });
    const everything = (await req('GET', '/super/all-vehicle-sales?limit=100', undefined, S)).body.items || [];
    const oldRow = everything.find((x: any) => x.id === legacy.id);
    check('an older sale without owner fields still appears, owned by its shop', !!oldRow && oldRow.ownerType === 'SHOP' && oldRow.shopId === A.shopId && oldRow.ownerName.startsWith('Audit Fix Shop'), oldRow);
  }

  console.log(`\n${failures === 0 ? 'ALL CHECKS PASSED' : failures + ' CHECK(S) FAILED'}. Run cleanup-test-data.ts to remove "Audit Fix Shop" data.`);
  process.exit(failures === 0 ? 0 : 1);
}
main().catch((e) => { console.error('Test crashed:', e); process.exit(1); });
