import { IsEmail, IsNotEmpty, IsString, IsOptional, MinLength, Matches, IsNumber } from 'class-validator';
import { PHONE_REGEX, PHONE_REGEX_MESSAGE } from '../../common/validators/phone';

export class LoginDto {
  // Accepts either the account's email address OR its mobile number - both
  // are valid login identifiers sharing the same password (see
  // AuthService.login). Kept as `email` (rather than renaming to
  // `identifier`) to avoid a breaking API change; validation is relaxed to
  // a plain non-empty string since a phone number isn't valid email format.
  @IsString()
  @IsNotEmpty({ message: 'Email address or mobile number is required' })
  email: string;

  @IsString()
  @IsNotEmpty({ message: 'Password is required' })
  password: string;

  // Sent by the frontend so the backend can tell a browser login apart from
  // the native Android/iOS app (Capacitor.isNativePlatform()). Optional and
  // defaults to 'web' when omitted, so older/unaware clients are still
  // treated as web for the Shop Admin web-login restriction below.
  @IsOptional()
  @IsString()
  platform?: string; // 'web' | 'native'
}

export class ChangePasswordDto {
  @IsString()
  @IsNotEmpty({ message: 'Old password is required' })
  oldPassword: string;

  @IsString()
  @IsNotEmpty({ message: 'New password is required' })
  @MinLength(6, { message: 'New password must be at least 6 characters long' })
  newPassword: string;
}

export class ResetPasswordPublicDto {
  @IsString()
  @IsNotEmpty()
  identifier: string;

  @IsString()
  @IsNotEmpty()
  method: string; // 'email' | 'phone'

  @IsString()
  @IsNotEmpty()
  @MinLength(6, { message: 'New password must be at least 6 characters long' })
  newPassword: string;
}

export class SendOtpDto {
  @IsString()
  @IsNotEmpty()
  identifier: string;

  @IsString()
  @IsNotEmpty()
  method: string; // 'email' | 'phone'

  @IsString()
  @IsNotEmpty()
  purpose: string; // 'register' | 'reset' | 'customer_verify' etc.
}

export class VerifyOtpDto {
  @IsString()
  @IsNotEmpty()
  identifier: string;

  @IsString()
  @IsNotEmpty()
  method: string;

  @IsString()
  @IsNotEmpty()
  purpose: string;

  @IsString()
  @IsNotEmpty({ message: 'OTP code is required' })
  code: string;
}

// Public self-registration wizard's payload - two steps on the frontend:
// Step 1 (basic details - name, shop name, address+GPS, city, state, PIN
// code, optional Aadhaar number, email, OTP-verified mobile number,
// password, all in one flat form) and Step 2 (plan + payment only).
// Both email and phone double as login identifiers post-registration (see
// AuthService.login) and must each be unique across all shop accounts -
// enforced in AuthService.registerShop().
export class RegisterShopDto {
  @IsString()
  @IsNotEmpty()
  shopName: string;

  @IsString()
  @IsNotEmpty()
  ownerName: string;

  @IsEmail({}, { message: 'Please enter a valid email address' })
  @IsNotEmpty({ message: 'Email address is required' })
  email: string;

  @IsString()
  @IsNotEmpty()
  @Matches(PHONE_REGEX, { message: PHONE_REGEX_MESSAGE })
  phone: string;

  // References a ShopCategory row (see shop-category module), picked from
  // the Super-Admin-curated dropdown on the registration form. Defines what
  // "type" of shop this account is (e.g. Dealers).
  @IsString()
  @IsNotEmpty({ message: 'Please select a shop category' })
  categoryId: string;

  @IsString()
  @IsNotEmpty()
  location: string;

  // City & state are auto-filled on the frontend from reverse-geocoding the
  // GPS position captured by the "Current Location" button (Nominatim's
  // district/state fields - see geo.controller.ts) but stay editable, so
  // they're still required here rather than derived server-side.
  @IsString()
  @IsNotEmpty()
  city: string;

  @IsString()
  @IsNotEmpty()
  state: string;

  @IsString()
  @IsNotEmpty()
  @Matches(/^\d{6}$/, { message: 'PIN code must be exactly 6 digits' })
  pinCode: string;

  // Optional - captured as a plain 12-digit number (not an uploaded
  // document) and encrypted at rest, see AuthService.registerShop().
  @IsOptional()
  @IsString()
  @Matches(/^\d{12}$/, { message: 'Aadhaar number must be exactly 12 digits' })
  aadhaarNumber?: string;

  @IsString()
  @IsNotEmpty()
  @MinLength(6)
  password: string;

  @IsString()
  @IsNotEmpty()
  plan: string; // 'MONTHLY' | 'HALF_YEARLY' | 'YEARLY' (the free trial plan has been retired)

  // Captured alongside `location` by the "Current Location" GPS button (see
  // captureShopLocation in App.jsx) - optional since a shop owner can type
  // the address manually instead of using GPS.
  @IsOptional()
  @IsNumber()
  latitude?: number;

  @IsOptional()
  @IsNumber()
  longitude?: number;

  // Optional referral code entered by the new shop owner, generated by another
  // shop admin via the "Refer" button in Shop Settings. Validated against
  // existing Shop.referralCode values in AuthService.registerShop().
  @IsOptional()
  @IsString()
  referralCode?: string;
}
